# --- IDENTITY MANAGEMENT (Authentik UI) ---
auth.wallage.org.uk, auth.garywallage.uk, auth.catherinewallage.uk {
    import cloudflare_tls
    import performance

    handle /outpost.goauthentik.io/* {
        reverse_proxy authentik-server:9000 {
            header_up Host {host}
        }
    }

    handle {
        reverse_proxy authentik-server:9000 {
            import proxy_optimizations
        }
    }
}

# --- SWARM MANAGEMENT (Portainer) ---
portainer.wallage.org.uk {
    import cloudflare_tls
    import performance
    import authentik
    reverse_proxy core-infra_portainer:9443 {
        import proxy_optimizations
        transport http {
            tls_insecure_skip_verify
        }
    }
}
