# --- HOME ASSISTANT ---
ha.wallage.org.uk {
    import cloudflare_tls
    reverse_proxy home-assistant_homeassistant:8123 {
        import proxy_optimizations
    }
}

# --- IOT & EDGE PROXY ---
zigbee.wallage.org.uk {
    import cloudflare_tls
    import performance
    import authentik
    reverse_proxy 192.168.1.3:8080 {
        import proxy_optimizations
    }
}

# --- PRIVACY & DOWNLOADS ---
transmission.wallage.org.uk {
    import cloudflare_tls
    import performance
    reverse_proxy privacy-media_transmission:9091 {
        import proxy_optimizations
    }
}
