# LazyLibrarian Automation Panel
books-manage.wallage.org.uk {
    reverse_proxy lazylibrarian:5299
}

# Kavita Document & Layout Library
kavita.wallage.org.uk {
    reverse_proxy kavita:5000
}

# Audiobookshelf Media Cloud Reader
abs.wallage.org.uk {
    reverse_proxy audiobookshelf:80
}
