staging.garywallage.uk, wedding.garywallage.uk, family.garywallage.uk, fashion.garywallage.uk, cosplay.garywallage.uk, glamour.garywallage.uk, boudoir.garywallage.uk {
    import cloudflare_tls
    import performance

    # 1. Protect Admin paths
    # When a user hits these, the 'authentik' snippet kicks in
    @admin {
        path /wp-admin* /wp-login.php* /wp-login*
        not path /wp-admin/admin-ajax.php*
        } 
    handle @admin {
        import authentik
        reverse_proxy gary-portfolio_web:80 {
            import proxy_optimizations
        }
    }

    # 2. Public paths
    # No Authentik check here—the public can see the portfolios
    handle {
        reverse_proxy gary-portfolio_web:80 {
            import proxy_optimizations
        }
    }

    # 3. GLOBAL CALLBACK HANDLER
    # This ensures that even if you aren't on an /admin path, 
    # the Authentik 'handshake' can still complete.
    handle /outpost.goauthentik.io/* {
        import authentik
    }
}
