staging.garywallage.uk, wedding.garywallage.uk, family.garywallage.uk, fashion.garywallage.uk, cosplay.garywallage.uk, glamour.garywallage.uk, boudoir.garywallage.uk {
    import cloudflare_tls
    import performance

    reverse_proxy gary-portfolio_web:80 {
        import proxy_optimizations
    }
}
