# --- SANCTUM API GATEWAY (Direct Access for Android APK & Web Client) ---
sanctum-api.wallage.org.uk {
    import cloudflare_tls
    import performance

    reverse_proxy sanctum_api:8000 {
        import proxy_optimizations
    }
}

# --- SANCTUM ADMIN & WEB INTERFACE (Native Google & Sanctum JWT Auth) ---
sanctum-admin.wallage.org.uk {
    import cloudflare_tls
    import performance

    reverse_proxy sanctum_admin:80 {
        import proxy_optimizations
    }
}
